# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVO7PgK32GYOa4iceAZQ_EZlukMTAKRc
"""



def chatbot_response(user_input):
    user_input = user_input.lower().strip()

    responses = {
        "hello": "Hello! How can I help you?",
        "hi": "Hi! Nice to meet you.",
        "hey": "Hey! How can I help you?",
        "how are you": "I am fine. Thank you for asking!",
        "what is your name": "I am a simple Rule-Based Chatbot.",
        "who are you": "I am a chatbot created using Python.",
        "what can you do": "I can answer some predefined questions.",
        "thank you": "You're welcome!",
        "thanks": "You're welcome!",
        "bye": "Goodbye! Have a nice day."
    }

    if user_input in responses:
        return responses[user_input]

    if "hello" in user_input or "hi" in user_input:
        return "Hello! How can I help you?"

    if "name" in user_input:
        return "I am a simple Rule-Based Chatbot."

    if "help" in user_input:
        return "Sure! You can ask me about my name or what I can do."

    return "Sorry, I don't understand that. Please try another question."


def main():
    print("===================================")
    print("       RULE-BASED CHATBOT")
    print("===================================")
    print("Type 'bye' to exit the chatbot.")
    print()

    while True:
        user_input = input("You: ")
        response = chatbot_response(user_input)

        print("Bot:", response)

        if user_input.lower().strip() == "bye":
            break


main()